server:
  port: 5000
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cnbbf50l5elc73fjuka0-a.frankfurt-postgres.render.com/acasa_db
    username: acasa_db_user
    password: 5fn6c3Mjka5a9DVrMznu8srrHTXxXGLH
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

