server:
  port: 5000
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cphs2t21hbls73b8hma0-a.singapore-postgres.render.com/acasa_db_879k
    username: acasa_db_879k_user
    password: RSgnMkwgAIbSNx1zXy9DfIbQpxX1KtrQ
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

